package olivetv

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/imroc/req/v3"
	"github.com/violetpupil/gos/std/strings"
)

func init() {
	registerSite("tiktok", &tiktok{})
}

type tiktok struct {
	base
}

func (this *tiktok) Name() string {
	return "tiktok"
}

func (this *tiktok) RoomID(roomURL RoomURL) string {
	s := strings.TrimSuffix(string(roomURL), "/live")
	s = strings.SplitLast(s, "@")
	return ""
}

func (this *tiktok) RoomURL(roomID string) RoomURL {
	return RoomURL(fmt.Sprintf("https://www.tiktok.com/@%s/live", roomID))
}

type TiktokAutoGenerated struct {
	Data struct {
		Status int    `json:"status"`
		Title  string `json:"title"`
		Owner  struct {
			Nickname string `json:"nickname"`
		} `json:"owner"`
		StreamURL struct {
			RtmpPullURL string `json:"rtmp_pull_url"`
			FlvPullURL  struct {
				FullHd1 string `json:"FULL_HD1"`
				Hd1     string `json:"HD1"`
				Sd1     string `json:"SD1"`
				Sd2     string `json:"SD2"`
			} `json:"flv_pull_url"`
			HlsPullURL string `json:"hls_pull_url"`
		} `json:"stream_url"`
	} `json:"data"`
}

// set 抓取直播间信息
func (this *tiktok) set(tv *TV) error {
	liveURL := string(this.RoomURL(tv.RoomID))
	c := req.C()
	if tv.proxy != "" {
		c.SetProxyURL(tv.proxy)
	}
	resp, err := c.R().SetHeaders(map[string]string{
		"Referer":    liveURL,
		"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
	}).Get(liveURL)
	if err != nil {
		return err
	}
	if resp.GetStatusCode() != http.StatusOK {
		return errors.New("tiktok: network not available " + resp.GetStatus())
	}

	// TODO
	return nil
}
